export const HardSkills = [
	{ skill: "Figma.png", skillName: "" },
	{ skill: "UI-&-UX.png", skillName: "" },
	{ skill: "Python.png", skillName: "" },
	{ skill: "Visual-Studio-Code.webp", skillName: "VS Code" },
	{ skill: "HTML.webp", skillName: "" },
	{ skill: "CSS.png", skillName: "" },
	{ skill: "Bootstrap.png", skillName: "" },
	{ skill: "Java-Script.webp", skillName: "" },
	{ skill: "TypeScript.png", skillName: "" },
	{ skill: "Git.png", skillName: "" },
	{ skill: "GitHub.png", skillName: "" },
	{ skill: "XAMP.png", skillName: "" },
	{ skill: "PHP.png", skillName: "" },
	{ skill: "Java.png", skillName: "" },
	{ skill: "MySQL.png", skillName: "" },
	{ skill: "Node-Js.png", skillName: "" },
	{ skill: "Prisma.png", skillName: "" },
	{ skill: "React.png", skillName: "" },
	{ skill: "PostgreSQL.png", skillName: "" },
	{ skill: "MongoDB.png", skillName: "" },
	{ skill: "Windows.png", skillName: "" },
	{ skill: "Portugol-Studio.png", skillName: "Portugol" },
	{ skill: "Arduino.png", skillName: "" },
	{ skill: "Docker.webp", skillName: "" },
];